print('Hello, world')
print('what's your name?')
print('tudo bem?')
print('oii')
print('que sono')
print('good morning')
print('byee')
print('beautiful')
print('help')
print('good afternoon')